version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ipl_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:Sachhit@1045@db.rtelbynczmlccvrrkpoe.supabase.co:5432/postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: ipl_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules